# Generated by Django 6.0.6 on 2026-06-30 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksite_functions', '0002_order_orderitem_order_booksite_fu_created_d862df_idx'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'Book', 'verbose_name_plural': 'Books'},
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.TextField(verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='booksite_functions.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.CharField(max_length=150, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='book',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='books/', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='book',
            name='stock',
            field=models.CharField(choices=[('y', 'In stock'), ('n', 'Out of stock')], default='y', max_length=1, verbose_name='Stock status'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=20, verbose_name='Title'),
        ),
    ]
